version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
cache: packages -> **\packages.config
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: Mnemosyne2Reborn\bin\Release\
  name: Mnemosyne-Reborn
  type: zip
deploy:
- provider: GitHub
  release: Mnemosyne-2.0 v$(appveyor_tag_name)
  auth_token:
    secure: f47v+SsAj4FXY3D5EQX449lYVmm2rP20prLGvTefDG0SICNHqE7OK9xMuABjJlH1
  artifact: Mnemosyne-Reborn
  draft: false
  force_update: false
  on:
    branch: master
    appveyor_repo_tag: true